### PR TITLE
Fix frontend test

### LINKED ISSUE #336: Fix front-end tests
## Description
 Some front-end tests are failing, we need to fix them so we can start working on CI issues

## Acceptance Criteria

- [ ] All tests pass

### PR DESCRIPTION
**Pull request by harristomy**
Refactored some frontend tests to enable passable tests

Closes #336

### CODE REVIEW

**Review by Dj5822 — APPROVED** [review]
I like how you added error alerts in the EncountersListPage, which will make the application more user friendly. One thing you could improve on is adding comments. Other than that it looks good.

**Comment by mdar365** [comment]
I'm getting this error for EditPerson.test.js, is it working for you?
image

**Comment by harristomy** [comment]
> I like how you added error alerts in the EncountersListPage, which will make the application more user friendly. One thing you could improve on is adding comments. Other than that it looks good.

Will do, cheers

**Comment by harristomy** [comment]
> I'm getting this error for EditPerson.test.js, is it working for you? image

Nah I think I got this at the start when auth wasn't setup properly but not now :/ Is .env and firebase-config unchanged when you switched to my fork?

**Review by skwe902 — COMMENTED** [review]
LGTM! - only thing is when I run the test I get this error: 
image
Says the test suite has failed to run

**Pull request merged**
