### PR TITLE
Update create/edit person page

### PR DESCRIPTION
**Pull request by rainasong**
- Fixed styling to match the style guide
- Fixed API calls to get data from the backend
- Fixed submit logic, covers both create and edit page, can now successfully POST or PUT a person and update database
- Fixed delete handling logic, update modal, can now successfully DELETE a person and update database
- Fixed change image button, now can fire up selecting file screen and selecting an image can update the avatar preview (might need to merge Hazel's pr to continue, and currently still have some issue when submitting the image to backend)
- Added placeholders for each input field
- Fixed input field, now can handle live updating
- Added type to button so not all buttons trigger the submit action
- Fixed routing on Person and PersonsList page to go to '/people/:id/edit' when clicking on the edit button (it was '/person/:id/edit)
- Added a toast generator helper function to replace duplicated code, updated all files used toast

Fixes most of #271 

**Demo:**
Screen Shot 2022-03-19 at 11 13 15 PM

### CODE REVIEW

**Review by lusicle — APPROVED** [review]
lgtm! 😃

**Review by cdra334 — APPROVED** [review]
Wow amazing! This is so much better than what I did. I'm sorry I've given you so much extra work to do.

**Comment by rainasong** [comment]
> Wow amazing! This is so much better than what I did. I'm sorry I've given you so much extra work to do.

No worries! Thanks so much for your hard work as well! The social media icons bit you did was really nice!

**Review by ckar364 — COMMENTED** [review]
In the CustomButton.module.css file, do we want the "font-size: 18px" in the ".Text" class to use global CSS rather than being hard-coded?

**Comment by rainasong** [comment]
> In the CustomButton.module.css file, do we want the "font-size: 18px" in the ".Text" class to use global CSS rather than being hard-coded?

Thanks for noticing it! I'll fix it when I do the global styling fixing tomorrow!

**Pull request merged**
