### PR TITLE
Added integration tests for `GET /encounters` route

### PR DESCRIPTION
**Pull request by jimwang6012**
Fixes: #217 

Added a set of tests for the `GET /encounters` route as shown below:

image

### CODE REVIEW

**Comment by sdiv877** [comment]
Looks good, thanks for adding the tests! Might just have to resolve the conflict 👍

**Review by UoA-sjer215 — DISMISSED** [review]
lgtm

**Comment by jimwang6012** [comment]
Merge conflicts resolved

**Review by sdiv877 — APPROVED** [review]
LGTM! Thanks for writing the tests!

**Review by UoA-sjer215 — APPROVED** [review]
lgtm

**Pull request merged**
