### PR TITLE
Created Persons page

### PR DESCRIPTION
**Pull request by lusicle**
Addresses Issue #59 
- Created Persons.js file
- Created Persons.module.css file
- Displays a list of people with a short summary
- Button to create a new person
- UI matches the latest UI design

### CODE REVIEW

**Review by rainasong — APPROVED** [review]
LGTM! Except for one small thing - currently when I tried person cards are not clickable, so you might want to double-check that in your next PR :)

**Comment by lin8231** [comment]
> LGTM! Except for one small thing - currently when I tried person cards are not clickable, so you might want to double-check that in your next PR :)

Yo, that's my fault hahah. I made the PersonCard component, I didn't know at the time that it needs to be clickable so it has no click receiving props right now. I'll be making a PR shortly to update this, should work after :)

**Comment by lin8231** [comment]
This whole components/ and Components/ thing is really getting to me lol. We should really merge these two into one. Let's create an issue for this and fix it

**Review by lin8231 — APPROVED** [review]
Keep up the good work :D

**Pull request merged**
