### PR TITLE
Encounters page (Part 1/2)

### PR DESCRIPTION
**Pull request by rainasong**
- Constructed base page structure
- Extracted a CustomAvatar component for easy variable passing
- Added infinite scroll feature (currently data is fake but somewhat simulate the API call)
- Encounter cards are hoverable and will show the preview on the right end of the screen
- Encounter cards are clickable and will show a modal pop up with encounter details

Todo: Still need to implement actual API calls, search result filter when updated search bar is ready, responsiveness when the screen size gets very large, and a link to the create new encounter page.

Demo as below:
Screen Shot 2022-03-15 at 6 03 44 PM
When hover on an Encounter card:
Screen Shot 2022-03-15 at 6 03 50 PM
When click on an Encounter card:
Screen Shot 2022-03-15 at 6 03 56 PM

Fixes part of #65

### CODE REVIEW

**Comment by lin8231** [comment]
Question:
Is this supposed to be aligned with the cards?
image

Like this in the UI design?
image

Or is that in the next PR?

**Comment by rainasong** [comment]
> Question: Is this supposed to be aligned with the cards?

The above screenshot is on larger screens, on smaller screens it look like this:
Screen Shot 2022-03-15 at 6 41 42 PM

**Comment by lin8231** [comment]
> > Question: Is this supposed to be aligned with the cards?
> 
> The above screenshot is on larger screens, on smaller screens it look like this: Screen Shot 2022-03-15 at 6 41 42 PM

Ahh I see, thanks for clarifying!

**Review by lin8231 — APPROVED** [review]
Amazing work as always :)

**Review by cdra334 — APPROVED** [review]
Looks very nice. The code looks so clean!

**Pull request merged**
