### PR TITLE
SearchBar component update

### LINKED ISSUE #264: Improve SearchBar component
## Description
 
Currently the search bar component only shows cancel button in the autocomplete mode, it'd be good to have it in the other mode as well. Also, would be good to have onKeyDown event for the 'enter' key to improve usability and be more user friendly.

## Acceptance Criteria

- [ ] Add cancel button if it's not in the autocomplete mode, if cancel button is clicked should return an empty string
- [ ] Add onKeyDown event for 'enter' key
- [ ] Adjust styles and add custom font for the placeholder

## Implementation details

n/a

## Testing notes

n/a

### PR DESCRIPTION
**Pull request by rainasong**
- Added onKeyDown event to handle 'enter' key press event
- Added clear button when it's not in autocomplete mode
- Adjusted styles, included custom font for placeholders

Fixes #264

### CODE REVIEW

**Review by lin8231 — DISMISSED** [review]
Omg, ty! Was going to make a PR for this haha

**Review by uoa-lchu090 — APPROVED** [review]
LGTM!

**Review by lin8231 — APPROVED** [review]
Reapproving after merge

**Review by lusicle — COMMENTED** [review]
lgtm 😃

**Review by lusicle — APPROVED** [review]

**Pull request merged**
