### PR TITLE
Add mui and enzyme dependencies

### PR DESCRIPTION
**Pull request by rainasong**
Added Material UI and enzyme dependencies.
Note: We are using React 17 but enzyme only have documentation up to React 16, so I installed using `npm i --save-dev enzyme` and did not install an adapter as there's no official one yet

### CODE REVIEW

**Comment by dkap937-209** [comment]
LGTM

**Review by noahjade — APPROVED** [review]
Love your work :tada: :tada: mvp for sure

**Review by dkap937-209 — COMMENTED** [review]
LGTM

**Review by dkap937-209 — APPROVED** [review]
LGTM

**Pull request merged**
