### PR TITLE
Search Bar Reformat

### PR DESCRIPTION
**Pull request by uoa-lchu090**
Search Bar with Autocomplete:
-switched filters so that it follows the backend logic: title, type, id
-made links direct to the person or encounter's page (/person/id or /encounters/id)

no Autocomplete:
-switched output to just the searchbar string
-backend will provide apis for filtering people and encounters, so only input string from searchbar is needed now
-searchbar will now only send out the string when the search icon is entered

### CODE REVIEW

**Review by noahjade — APPROVED** [review]
LGTM! Thanks for this :) In the future tho can we not commit the data changes to the App component? Its gonna cause merge conflict headaches haha 😅

**Review by rainasong — COMMENTED** [review]
We originally designed to receive filtered results as the user typing in the search bar, is there a specific reason why we changed it to only output when enter is hit now?

**Comment by uoa-lchu090** [comment]
> LGTM! Just have one question, we originally designed to receive filtered results as the user typing in the search bar, is there a specific reason why we changed it to only output when enter is hit now?

Yeah, so originally we were doing all the filtering stuff in the frontend, but we had a meeting yesterday and the backend people informed us that they can do the filtering instead. It would be more efficient to filter the backend, so that we don't have to load in all the data first, but we can't easily do an autocomplete feature if the filtering is in the backend. As such, we decided to keep the frontend filtering in the autocomplete version, but for the one used in the people and encounters page, the backend will filter it. If I recall correctly, all you really need is feed the string into an API call and it will give you back the filtered results.

**Comment by rainasong** [comment]
> > LGTM! Just have one question, we originally designed to receive filtered results as the user typing in the search bar, is there a specific reason why we changed it to only output when enter is hit now?
> 
> In terms of the enter function, I don't think it would be very efficient so that every time the string changes, an api call to the backend is made, but if you really want to, I can try and make it so that it does that.

That's reasonable, I think we can keep it this way for now!

**Review by rainasong — APPROVED** [review]

**Pull request merged**
