### PR TITLE
Created test files

### PR DESCRIPTION
**Pull request by sliu929**
Created new test files
Added Firebase admin dependency
Fixed outdated test code

### CODE REVIEW

**Review by lanxdrey19 — DISMISSED** [review]
LGTM :)

**Comment by sdiv877** [comment]
LGTM!

**Review by sdiv877 — DISMISSED** [review]

**Review by hajineats — APPROVED** [review]
LGTM

**Comment by hajineats** [comment]
it's hashtag 100 too!

**Review by sdiv877 — APPROVED** [review]
LGTM 👍

**Pull request merged**
