### PR TITLE
Add service to backend architecture

### LINKED ISSUE #39: Add service to the backend architecture
## Description
 
Service is a class that interacts directly with database and controllers make use of services to create a higher-order operations.

## Acceptance Criteria

- [ ] Create service folder 
- [ ] Service folder contains an example person.service.ts

## Implementation details

Got rid of database related imports from controller since controller no longer deals with database stuff (only service does)

## Testing notes

n/a

### PR DESCRIPTION
**Pull request by hajineats**
Service is now added as part of the architecture

### Architecture description:
**Controller** contains high-level operations using services, consumed by routes
**Route** configures endpoints, and attaches controller as an action to each route's REST methods
**Service** contains database operations
**Model** describes schema of a data type

fixes #39

### CODE REVIEW

**Comment by hajineats** [comment]
wait need to fix lint

**Review by butterplup — DISMISSED** [review]
I think this looks good

**Comment by hajineats** [comment]
@butterplup I need the approval again haha sorry

**Review by butterplup — DISMISSED** [review]
LGTM still

**Review by lin8231 — APPROVED** [review]
LGTM!

**Comment by sliu929** [comment]
Fixed some merge errors with the outdated person.model.ts

**Review by sliu929 — APPROVED** [review]
Merge errors fixed with person.model.ts

**Review by lanxdrey19 — APPROVED** [review]
LGTM :)

**Review by UoA-sjer215 — APPROVED** [review]

**Review by butterplup — APPROVED** [review]
Still good.

**Pull request merged**
