### PR TITLE
[#360] - Fixed labels nto showing on person card

### LINKED ISSUE #360: Fix labels not showing up on person cards
## Description
Label chips are not showing on person cards. Labels are showing correctly on the drawers but not the cards

## Acceptance Criteria

- [ ] Labels can be seen on the person card on the person list page as chips

### PR DESCRIPTION
**Pull request by henrym25**
Fixed labels not appearing on person card. Labels should now render correctly as chips on the person card on the person list page

### CODE REVIEW

**Comment by BraveNewWord** [comment]
LGTM this is what the chips look like from my end

image

**Review by BraveNewWord — DISMISSED** [review]
LGTM this is what the chips look like from my end

image

**Review by hmit106 — CHANGES_REQUESTED** [review]
When creating a person with no labels, an unsightly empty chip appears where the labels would otherwise be. I suggest removing this, as not every person would need labels.

image

**Review by hmit106 — APPROVED** [review]
All issues resolved, LGTM!

**Pull request merged**
