### PR TITLE
Implemented get encounter endpoint with auth

### PR DESCRIPTION
**Pull request by sliu929**
Tested manually via Postman.
Unit tests are to be done later.

FIXED:  Issue #36

### CODE REVIEW

**Review by sher812 — APPROVED** [review]
LGTM

**Review by lanxdrey19 — APPROVED** [review]
LGTM

**Review by sher812 — APPROVED** [review]
LGTM

**Comment by sliu929** [comment]
Fixed merge errors

**Review by UoA-sjer215 — APPROVED** [review]
lgtm

**Pull request merged**
