### PR TITLE
Person card (full ver) Part 2/2: Logic

### LINKED ISSUE #60: Create Person Card Component
## Description
 
Person Card component that Displays a summary of info about a particular person. Will be displayed on the Persons Page and possibly elsewhere.
image

## Acceptance Criteria

- [x] Shows the name of a person
- [x] Shows the profile picture of the person
- [x] Shows single line summary of information
- [x] Shows number of encounters
- [x] Shows Date last met
- [x] Shows more options button to quickly access edit and delete options
- [x] Shows other details such as links to social media, etc.

## Implementation details

* Uses latest UI design once available
* Created as component to be used in various places

## Testing notes

* Test information is accurate and correctly displayed

## Reviewers

@jyao244

### PR DESCRIPTION
**Pull request by lin8231**
* Implemented logic for person card
* Fully dynamic now, accepts props and displays things accordingly
* Created a icon renderer helper function for social media icons
* Added a bunch more tests
* First met dates are calculated dynamically based current time minus first met time, always uses human-readable language, e.g.  "today",  "3 days ago", "2 years ago"
  * Displays "once upon a time" if no first-met date. I.e. "First met once upon a time

This component takes the following props:

```js
PersonCard.propTypes = {
  id: PropTypes.string,
  name: PropTypes.string.isRequired,
  img: PropTypes.string,
  socialMedias: PropTypes.arrayOf(PropTypes.string),
  numEncounters: PropTypes.number,
  lastMet: PropTypes.instanceOf(Date),
  onEdit: PropTypes.func.isRequired,
  onDelete: PropTypes.func.isRequired,
  firstMet: PropTypes.instanceOf(Date),
};
```

This PR along with #98 fixes #60 

## Demo
Normal, no hover:
image

Hover:
image

Menu button hover:
image

Menu button clicked:
image

Menu item hovered:
image

If there are more than two social medias, it collapses:
image

### CODE REVIEW

**Review by noahjade — DISMISSED** [review]
Beautiful!! 🎉 🎉 LGTM :)

**Comment by rainasong** [comment]
LGTM!!

**Review by rainasong — APPROVED** [review]

**Review by noahjade — APPROVED** [review]
LGTM! ✨

**Review by rainasong — APPROVED** [review]
Beautiful!

**Pull request merged**
