### PR TITLE
Set up frontend project + Linting rules

### LINKED ISSUE #16: Set up frontend repo
## Description
The project's frontend codebase requires initial set-up.

## Acceptance Criteria

- [x] Create react app
- [x] TS enabled

## Implementation details
n/a

## Testing notes
n/a

### LINKED ISSUE #17: ESLint setup for frontend
## Description
Linting rules need to be set up to ensure consistent code style across the team. 
 
## Acceptance Criteria

- [x] ESLint dependency 
- [x] ESLint works properly for TS and TSX files 
- [x] Appropriate rules for style are added 
- [x] ESLint can be run through the command line
- [x] Optional: config ESLint auto-format on save for VS Code 

## Implementation details
n/a

## Testing notes
n/a

### PR DESCRIPTION
**Pull request by lin8231**
* Create base Typescript React project through `create-react-app`
* Customised a few things on the template (E.g. document name)
* Set up ESLint for the project
  * The rules I used were just some basic/typical rules for TS React. If you have a strong objection towards anything, I'm keen to discuss
  * To run in the command line, use `eslint <file_path>` from within the `forgettable-frontend` directory.
    * **If you use VS Code**, I've added VS Code support for format-on-save, so you won't need to run ESLint manually ever. To use, please make sure you **have the ESLint extension installed and enabled** - then it should simply work, the config is already done. 

Fixes #16 
Fixes #17

**Note:** Since the team has decided to use npm as the package manager, please exclusively use `npm` for your dependencies.

### CODE REVIEW

**Review by noahjade — APPROVED** [review]
Lets go!! Thank you for setting this up :) Looks great 🎉

**Review by butterplup — COMMENTED** [review]
Does the package-lock file need to be committed? This is just a general question?

**Review by butterplup — CHANGES_REQUESTED** [review]
Would you be able to add support for prettier as well?

**Comment by lin8231** [comment]
> Does the package-lock file need to be committed? This is just a general question?

Package lock helps make sure that everyone on the team is using the same version of the dependencies. I personally dislike such a huge file as well, but [npm highly recommends that it is committed](https://docs.npmjs.com/cli/v6/configuring-npm/package-locks)

**Comment by lin8231** [comment]
> Would you be able to add support for prettier as well?

Thanks for bringing this up, it's a really good point you raised there. I think generally unless it's easier not to mix formatter/litners since it can lead to annoying formatting conflicts. And in this case, anything that Prettier can already be done by ESLint, so not sure if it's very worthwhile unless people have strong attachments to their Prettier formatters. WDYT?

Side note: these formatting rules are (intentionally) frontend specific are made to only apply for the frontend app, so backend would need to choose its own linter and codestyle.

**Review by butterplup — APPROVED** [review]
Okay, that's understandable. If formattings rules are included with ESLint then I think that's sufficient. LGTM!

**Pull request merged**
