### PR TITLE
Auth logic + routing revamp (Token invalidation handling, session maintenance, etc)

### LINKED ISSUE #276: Fix Firebase auth in frontend and add error/invalidation handling logic
## Description
 
Currently you are required to log in every time you refresh the page, which is not a very ideal user experience. 
Auth logic needs a revamp to make sure that this doesn't happen, and add loading screens and error handling etc. 
Also, there is no logic to sign the user out automatically when a token has expired. This means that the user get stuck in a limbo signed-in-but-nothing-works state

## Acceptance Criteria

- [ ] Refreshing does not require user to sign in again 
- [ ] Session is maintained
- [ ] If token is invalidated, the user is signed out and redirected to sign in screen
- [ ] User can sign in properly
- [ ] User can have an account created when signing in if they don't have one already
- [ ] Other auth logic all work properly 
- [ ] Can sign out properly

### LINKED ISSUE #277: Reorganise routes to be cleaner
## Description
 
Currently routes are all rendered in App.js, and the loggedIn/logginIn/notLoggedIn states are not handled very comprehensively. 
This should be moved out into a router component which handles all the conditional logic

## Acceptance Criteria

- [ ] Page router can route to all existing pages without breaking them
- [ ] Page router can handle different states and conditionally render routes
- [ ] Page router accounts for NavBar
- [ ] There is no more routing logic in App.js

### PR DESCRIPTION
**Pull request by lin8231**
Buckle up bois and girls.. I changed a loooot of things in this PR, so please bear with me:
* Created an AuthContext, which wraps the app content - 
  * has information on the user and whether they are logged in and other meta information 
* Redid authentication, added auth.js. 
  * This does and encapsulates all auth related things 
* Created a PageRouter
  * Responsive for all things routing related
  * Encapsulates routing logic 
  * Does more comprehensive conditional rendering of routes 
    * Not signed in / signing in / signed in
* Remade page for signing in
  * More comprehensive responsiveness (Responsive in all directions)
  * Moved auth logic out of this. It is now a stateless logicless component 
    * All auth logic is delegated to the auth file through the auth context.
 * Updated JWT logic
   * No longer stored in localStorage - no longer a security concern
   * Token is dynamically pulled every time from firebase directly, no need to worry about it expiring or something
 * Added logic for handling if token is invalidated
   * User is logged out and redirected to sign in 
 * Auth sessions are now maintained
   * App no longer makes you sign in every time you refresh 
* A number of other small things... 

* Loading page needs prettifying and a number of other things need tidying up, will come in a future PR, this one is chonky enough as it is

Fixes #276 
Fixes #277 

## Demo

Demo shows signing in, loading screen (to be prettified), session persists through refreshing, all pages still work, data being pulled correctly with firebase direct token, log out works with new auth 

https://user-images.githubusercontent.com/62003343/159120322-6b8c5671-ca48-481f-b03c-e69e92272fc4.mp4

### CODE REVIEW

**Review by noahjade — DISMISSED** [review]
You are a absolute legend for sorting out all this Auth stuff 🚀 🚀

**Review by hajineats — APPROVED** [review]
Good read

**Review by hajineats — APPROVED** [review]
LGTM

**Review by lusicle — APPROVED** [review]
LGTM 😃

**Pull request merged**
