### PR TITLE
Update person drawer to have option to be displayed as static drawer

### LINKED ISSUE #147: Update person drawer to have option to be displayed as static drawer
## Description
* Currently, the PeronDrawer component is made for the purpose of the Dashboard and the People list page
  * In this implementation, it is displayed on the right side, as a collapsible drawer (See below)
  * image

* We also need a version of this component that exists on the leftside for the "Person" page (see below:
  * image

## Acceptance Criteria

- [ ] Drawer conditionally renders on left/right depending on a bool prop
- [ ] Styling changes accordingly and correctly depending on which version it is 
- [ ] Does not break existing styles 
- [ ] Shows "Edit" button if is the static version 

## Implementation details

n/a

## Testing notes

n/a

### PR DESCRIPTION
**Pull request by lin8231**
* Currently, the PeronDrawer component is made for the purpose of the Dashboard and the People list page
  * In this implementation, it is displayed on the right side, as a collapsible drawer (See issue #147) 
* We also need a version of this component that exists on the leftside for the "Person" page (see issue #147)
* Created prop to pass in conditional variable `staticDrawer`, and change the component's styling conditionally
* Updated CustomButton to be more customisable.

Fixes #147

## Updated Props

```js
PersonDrawer.propTypes = {
  open: PropTypes.bool.isRequired,
  id: PropTypes.string,
  name: PropTypes.string.isRequired,
  img: PropTypes.string,
  socialMedias: PropTypes.arrayOf(Object), // See below for an example
  // [{name: 'facebook', link: 'https://www.google.com/'}, {name: 'instagram', link: 'https://www.google.com/'}]
  firstMet: PropTypes.instanceOf(Date),
  location: PropTypes.string,
  interests: PropTypes.arrayOf(PropTypes.string),
  staticDrawer: PropTypes.bool,
  onEdit: PropTypes.bool,
};
```

## Demo

When  `staticDrawer={false}`
image

When `staticDrawer={true}`
image

### CODE REVIEW

**Review by lusicle — APPROVED** [review]
lgtm :)

**Review by cdra334 — APPROVED** [review]
Very nice work!

**Review by butterplup — APPROVED** [review]
Wow this LGTM ❗️

**Review by rainasong — COMMENTED** [review]
LGTM!

**Pull request merged**
