### PR TITLE
Fix loop logic in get persons endpoint controller

### PR DESCRIPTION
**Pull request by AdamAWiener**
Addresses #288 

Fixed for loop which fetches `person` details in `getPersonWithId()`. Had an issue with the iteration logic where `i++` was replaced with `i+1` due to a auto formatting change.

### CODE REVIEW

**Review by lin8231 — APPROVED** [review]
Nice catch! Thanks for fixing this

**Review by sher812 — APPROVED** [review]
LGTM

**Review by lanxdrey19 — APPROVED** [review]
LGTM

**Comment by butterplup** [comment]
i dont know how approve on my phone

**Pull request merged**
