### PR TITLE
Create all frontend API call functions 

### LINKED ISSUE #167: Add a collection of API call functions
## Description
 
For easy reuse across the app, a collection of functions wrapping Axios API calls is required to speed up the development.

## Acceptance Criteria

- [ ] Each API call function should work without errors
- [ ] Each API call function should accept and pass on all parameters required by the backend

## Implementation details

Use Axios library to speed up the development

## Testing notes

Ensure all the ACs above are checked

### LINKED ISSUE #171: Create frontend API call functions
## Description
API calls are made from many different areas of the app, and many are repeated. We need a set of functions which does all the API call logic, so the pages can just call these functions rather than implementing its own logic. 

## Acceptance Criteria

- [ ] All user APIs are functional 
- [ ] All Person APIs are functional
- [ ] All Encounter APIs are functional 
- [ ] All API calls have error handling logic
- [ ] Functions are tested. 

## Implementation details

n/a

## Testing notes

n/a

### LINKED ISSUE #177: Add tests for API calls (frontend)
## Description
 
A suite of tests is needed to ensure API call helpers are correct and functional as expected.

## Acceptance Criteria

- [x] There should be at least one test to cover each function
- [x] The tests should mock API calls
- [x] All tests should pass

## Implementation details

Can use jest library to mock axios and API calls

## Testing notes

n/a

### PR DESCRIPTION
**Pull request by lin8231**
* Created some helper functions for abstracting repeated code of HTTP requests
* Created all API call functions 
* **Token is retrieved from localStorage**
  * Currently signIn is not storing token anywhere, this needs to be done @dkap937-209 
  * Until this is merged ^, get a jwt and manually create a local storage item called "token" before attempting to call APIs. See below:
  * image
* Wrote a bunch of jsdocs for these, should hopefully be helpful when picking which function to use?
* Server URL to be updated/moved

Fixes #171 and #177

### CODE REVIEW

**Review by noahjade — DISMISSED** [review]
LGTM! Great work on this 🎉  Keen to get this merged in so I can play around with shifting the auth around/putting it in local storage.

**Review by cdra334 — DISMISSED** [review]
Very impressive. Thank you so much for all your hard work.

**Review by noahjade — APPROVED** [review]
Nice tests!! Thanks for adding those! LGTM 🌷

**Review by cdra334 — APPROVED** [review]
All the tests look good!

**Pull request merged**
