### PR TITLE
Created Button component

### PR DESCRIPTION
**Pull request by dkap937-209**
Fixes issue #62

### CODE REVIEW

**Comment by hajineats** [comment]
Needs eslint to be configured more loosely @lin8231

**Review by hajineats — APPROVED** [review]
LGTM!

**Review by noahjade — COMMENTED** [review]
Did we decide the different types of button styling was out of scope? It looks like this one only makes one kind of button, but the ticket implies it should make multiple?

**Comment by dkap937-209** [comment]
> Did we decide the different types of button styling was out of scope? It looks like this one only makes one kind of button, but the ticket implies it should make multiple?

I think what was decided is that it was only supposed to be the text-only buttons. And with the text-only buttons, it was either black or red. The red button was only used for deleting an account which I believe we have decided not to do for now.

**Comment by hajineats** [comment]
> Did we decide the different types of button styling was out of scope? It looks like this one only makes one kind of button, but the ticket implies it should make multiple?

@noahjade Ahh the ticket must've not been updated for that. At the moment red/black button is out of scope.

**Review by noahjade — APPROVED** [review]
Thanks for updating me about the scope!! This looks great :)

**Pull request merged**
